language: php

sudo: true

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.2

env:
  global:
    - MOODLE_BRANCH=MOODLE_34_STABLE
    - MOODLE_BRANCH=MOODLE_35_STABLE
    - MOODLE_BRANCH=MOODLE_36_STABLE
    - MOODLE_BRANCH=MOODLE_37_STABLE
    - MOODLE_BRANCH=MOODLE_38_STABLE
    - MOODLE_BRANCH=MOODLE_39_STABLE
    - MOODLE_BRANCH=master
  matrix:
    - DB=pgsql
    - DB=mysqli

matrix:
  exclude:
    - php: 7.0
      env: DB-pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB-pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB-pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB-pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB-mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB-mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB-mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB-mysqli MOODLE_BRANCH=master


before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0.0
  - nvm use 14.0.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci dev-master
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
