<<<<<<< HEAD
name: release branch test
=======
name: STABLE branch test
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74

on: [push, pull_request]

jobs:
  citest:
    name: CI test
    env:
      IGNORE_PATHS: tests/fixtures
    runs-on: 'ubuntu-latest'

    services:
      postgres:
<<<<<<< HEAD
        image: postgres:13
=======
        image: postgres:10
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

      mariadb:
<<<<<<< HEAD
        image: mariadb:10.6.7
=======
        image: mariadb:10.5
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
        php: ['7.4', '8.0', '8.1']
        database: ['mariadb', 'pgsql']
        moodlebranch: ['MOODLE_401_STABLE']
        include:
          - node: 16.20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
=======
        include:
          - php: '7.3'
            moodle-branch: 'MOODLE_39_STABLE'
            database: 'mariadb'
            node: '14.15'
          - php: '7.3'
            moodle-branch: 'MOODLE_311_STABLE'
            database: 'mariadb'
            node: '14.15'
          - php: '7.3'
            moodle-branch: 'MOODLE_39_STABLE'
            database: 'pgsql'
            node: '14.15'
          - php: '7.3'
            moodle-branch: 'MOODLE_311_STABLE'
            database: 'pgsql'
            node: '14.15'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
        with:
          path: plugin

      - name: Install node  ${{ matrix.node }}
<<<<<<< HEAD
        uses: actions/setup-node@v3
=======
        uses: actions/setup-node@v2
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
        with:
          node-version: ${{ matrix.node }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql, mysqli, zip, gd, xmlrpc, soap
<<<<<<< HEAD
          ini-values: max_input_vars=5000
=======
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          # Add dirs to $PATH
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          # PHPUnit depends on en_AU.UTF-8 locale
          sudo locale-gen en_AU.UTF-8
<<<<<<< HEAD

=======
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
      - name: Install Moodle
        run:  moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
<<<<<<< HEAD
          MOODLE_BRANCH: ${{ matrix.moodlebranch }}
=======
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74

      - name: Run phplint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: Run codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker

      - name: Run validate
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Run savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Run mustache
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

<<<<<<< HEAD
      - name: Run grunt
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci grunt

      - name: Run phpdoc
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

=======
>>>>>>> 7da5b2a052c6c6a9a1f4b2c1f92eaf5b9ee45c74
      - name: Run phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit

      - name: Run behat
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome

      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd
